write-kubeconfig-mode: "640"
write-kubeconfig-group: "homelab-admin"
disable:
  - traefik
  - servicelb
  - local-storage
# Hardening guide
# See https://docs.k3s.io/security/hardening-guide#configuration-for-kubernetes-components
# ====================
secrets-encryption: true
protect-kernel-defaults: true
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction,EventRateLimit"
  - "admission-control-config-file=/etc/rancher/k3s/admission.yaml"
  - "audit-policy-file=/etc/rancher/k3s/audit.yaml"
  - "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "service-account-extend-token-expiration=false"
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=100"
kubelet-arg:
  - "streaming-connection-idle-timeout=5m"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
# ====================
