# Important: Key mappings are defined in karabiner-elements. 
# The reason is Aerospace does not support the `fn` modifier yet. 
# See https://github.com/nikitabobko/AeroSpace/issues/587

start-at-login = true
key-mapping.preset = "qwerty"

default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]

inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10
